export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';

export const PRODUCT_DATA_REQUEST = 'PRODUCT_DATA_REQUEST';
export const PRODUCT_DATA_SUCCESS = 'PRODUCT_DATA_SUCCESS';
export const PRODUCT_DATA_ERROR = 'PRODUCT_DATA_ERROR';

export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';